-- Create the medical_records table
CREATE TABLE public.medical_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  title TEXT NOT NULL,
  record_date DATE NOT NULL,
  file_url TEXT,
  CONSTRAINT medical_records_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.medical_records ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows users to view their own medical records
CREATE POLICY "Allow users to view their own records"
ON public.medical_records
FOR SELECT
USING (auth.uid() = user_id);

-- Create a policy that allows users to insert their own records
CREATE POLICY "Allow users to insert their own records"
ON public.medical_records
FOR INSERT
WITH CHECK (auth.uid() = user_id);
